stages:
  - Stage

build_laravel:
  stage: Stage
  tags:
    - PHP_PROJECTS
  script:
    - rsync -avz --exclude 'public/.htaccess' -e 'ssh -o StrictHostKeyChecking=no -p 22' $CI_PROJECT_DIR/* ubuntu@3.109.28.118:/var/www/html/hair-skin-health/
    - |
      ssh -o StrictHostKeyChecking=no -p 22 ubuntu@3.109.28.118 << 'EOF'
        cd /var/www/html/hair-skin-health
        php artisan down
        php artisan config:clear
        php artisan cache:clear
        php artisan config:cache
        php artisan migrate --force
        php artisan l5-swagger:generate
        php artisan up
        sudo chmod -R 777 storage
      EOF
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'
  allow_failure: false

build_admin:
  stage: Stage
  tags:
    - REACTJS_RPOJECT
  before_script:
    - cd $CI_PROJECT_DIR/frontend/admin
    - rm -f .env
    - |
      echo "REACT_APP_API_URL=https://hair-skin-health.projectbeta.biz/api" > .env
      echo "REACT_APP_APP_NAME=Hair Skin Health - Admin Panel" >> .env
      echo "REACT_APP_VERSION=1.0.0" >> .env
      echo "VITE_API_URL=https://hair-skin-health.projectbeta.biz/api" >> .env
    - source ~/.bash_profile
    - nvm use 20.18.1
  script:
    - rm -rf build
    - npm install
    - npm run build
    - rsync -avz --exclude 'frontend/admin/.env' -e 'ssh -o StrictHostKeyChecking=no -p 22' $CI_PROJECT_DIR/frontend/admin/build/ ubuntu@3.109.28.118:/var/www/html/hair-skin-health/public/admin/
  rules:
  - changes:
      - frontend/admin/**
    if: '$CI_COMMIT_BRANCH == "stage"'
  - if: '$CI_COMMIT_BRANCH == "stage"'
  allow_failure: false

build_dermatologist:
  stage: Stage
  tags:
    - REACTJS_RPOJECT
  before_script:
    - cd $CI_PROJECT_DIR/frontend/dermatologist
    - rm -f .env
    - |
      echo "REACT_APP_API_URL=https://hair-skin-health.projectbeta.biz/api" > .env
      echo "REACT_APP_APP_NAME=Hair Skin Health - Dermatologist Panel" >> .env
      echo "REACT_APP_VERSION=1.0.0" >> .env
      echo "VITE_API_URL=https://hair-skin-health.projectbeta.biz/api" >> .env
    - source ~/.bash_profile
    - nvm use 20.18.1
  script:
    - rm -rf build
    - npm install
    - npm run build
    - rsync -avz --exclude 'frontend/dermatologist/.env' -e 'ssh -o StrictHostKeyChecking=no -p 22' $CI_PROJECT_DIR/frontend/dermatologist/build/ ubuntu@3.109.28.118:/var/www/html/hair-skin-health/public/dermatologist/
  rules:
  - changes:
      - frontend/dermatologist/**
    if: '$CI_COMMIT_BRANCH == "stage"'
  - if: '$CI_COMMIT_BRANCH == "stage"'  
  allow_failure: false

build_patient:
  stage: Stage
  tags:
    - REACTJS_RPOJECT
  before_script:
    - cd $CI_PROJECT_DIR/frontend/patient
    - rm -f .env
    - |
      echo "REACT_APP_API_URL=https://hair-skin-health.projectbeta.biz/api" > .env
      echo "REACT_APP_APP_NAME=Hair Skin Health - Patient Panel" >> .env
      echo "REACT_APP_VERSION=1.0.0" >> .env
      echo "VITE_API_URL=https://hair-skin-health.projectbeta.biz/api" >> .env
    - source ~/.bash_profile
    - nvm use 20.18.1
  script:
    - rm -rf build
    - npm install
    - npm run build
    - rsync -avz --exclude 'frontend/patient/.env' -e 'ssh -o StrictHostKeyChecking=no -p 22' $CI_PROJECT_DIR/frontend/patient/build/ ubuntu@3.109.28.118:/var/www/html/hair-skin-health/public/patient/
  rules:
  - changes:
      - frontend/patient/**
    if: '$CI_COMMIT_BRANCH == "stage"'
  - if: '$CI_COMMIT_BRANCH == "stage"'  
  allow_failure: false
